require: rubocop-packaging

AllCops:
  NewCops: enable
  Exclude:
    - '.bundle/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - tasks/*.rake
  ExcludedMethods:
    - configure
    - describe
    - context
    - shared_examples

Metrics/MethodLength:
  Exclude:
    - tasks/*.rake

Layout/LineLength:
  Max: 120
